// <auto-generated />
using System;
using GemaGestor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GemaGestor.Migrations
{
    [DbContext(typeof(WhitelabelContext))]
    [Migration("20260223075132_AddDescricaoEDataPedra")]
    partial class AddDescricaoEDataPedra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GemaGestor.Models.Pedras.Lote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<long>("TenancyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValorDeTrabalho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenancyId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Pedra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea");

                    b.Property<long?>("LoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Regiao")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDeTrabalho")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Pedra");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pedra");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GemaGestor.Models.Users.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("GemaGestor.Models.Users.Tenancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenancy");
                });

            modelBuilder.Entity("GemaGestor.Models.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("FormadaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LapidadaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LoteId")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<long?>("PedraId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<long?>("TenancyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FormadaId");

                    b.HasIndex("LapidadaId");

                    b.HasIndex("LoteId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PedraId");

                    b.HasIndex("TenancyId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Bruta", b =>
                {
                    b.HasBaseType("GemaGestor.Models.Pedras.Pedra");

                    b.Property<long>("TenancyId")
                        .HasColumnType("bigint");

                    b.HasIndex("TenancyId");

                    b.ToTable("Pedra", t =>
                        {
                            t.Property("TenancyId")
                                .HasColumnName("Bruta_TenancyId");
                        });

                    b.HasDiscriminator().HasValue("Bruta");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Formada", b =>
                {
                    b.HasBaseType("GemaGestor.Models.Pedras.Pedra");

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<int>("Formato")
                        .HasColumnType("integer");

                    b.Property<float>("Largura")
                        .HasColumnType("real");

                    b.Property<float>("Profundidade")
                        .HasColumnType("real");

                    b.Property<long>("TenancyId")
                        .HasColumnType("bigint");

                    b.HasIndex("TenancyId");

                    b.ToTable("Pedra", t =>
                        {
                            t.Property("Altura")
                                .HasColumnName("Formada_Altura");

                            t.Property("Formato")
                                .HasColumnName("Formada_Formato");

                            t.Property("Largura")
                                .HasColumnName("Formada_Largura");

                            t.Property("Profundidade")
                                .HasColumnName("Formada_Profundidade");

                            t.Property("TenancyId")
                                .HasColumnName("Formada_TenancyId");
                        });

                    b.HasDiscriminator().HasValue("Formada");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Lapidada", b =>
                {
                    b.HasBaseType("GemaGestor.Models.Pedras.Pedra");

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<int>("Formato")
                        .HasColumnType("integer");

                    b.Property<float>("Largura")
                        .HasColumnType("real");

                    b.Property<float>("Profundidade")
                        .HasColumnType("real");

                    b.Property<long>("TenancyId")
                        .HasColumnType("bigint");

                    b.HasIndex("TenancyId");

                    b.HasDiscriminator().HasValue("Lapidada");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Lote", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.Tenancy", "Tenancy")
                        .WithMany("Lotes")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Pedra", b =>
                {
                    b.HasOne("GemaGestor.Models.Pedras.Lote", "Lote")
                        .WithMany("Pedras")
                        .HasForeignKey("LoteId");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("GemaGestor.Models.Users.User", b =>
                {
                    b.HasOne("GemaGestor.Models.Pedras.Formada", null)
                        .WithMany("Formador")
                        .HasForeignKey("FormadaId");

                    b.HasOne("GemaGestor.Models.Pedras.Lapidada", null)
                        .WithMany("Lapidarios")
                        .HasForeignKey("LapidadaId");

                    b.HasOne("GemaGestor.Models.Pedras.Lote", null)
                        .WithMany("Donos")
                        .HasForeignKey("LoteId");

                    b.HasOne("GemaGestor.Models.Pedras.Pedra", null)
                        .WithMany("Donos")
                        .HasForeignKey("PedraId");

                    b.HasOne("GemaGestor.Models.Users.Tenancy", "Tenancy")
                        .WithMany("Users")
                        .HasForeignKey("TenancyId");

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GemaGestor.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Bruta", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.Tenancy", "Tenancy")
                        .WithMany("PedrasBrutas")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Formada", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.Tenancy", "Tenancy")
                        .WithMany("PedrasFormadas")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Lapidada", b =>
                {
                    b.HasOne("GemaGestor.Models.Users.Tenancy", "Tenancy")
                        .WithMany("PedrasLapidadas")
                        .HasForeignKey("TenancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenancy");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Lote", b =>
                {
                    b.Navigation("Donos");

                    b.Navigation("Pedras");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Pedra", b =>
                {
                    b.Navigation("Donos");
                });

            modelBuilder.Entity("GemaGestor.Models.Users.Tenancy", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("PedrasBrutas");

                    b.Navigation("PedrasFormadas");

                    b.Navigation("PedrasLapidadas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Formada", b =>
                {
                    b.Navigation("Formador");
                });

            modelBuilder.Entity("GemaGestor.Models.Pedras.Lapidada", b =>
                {
                    b.Navigation("Lapidarios");
                });
#pragma warning restore 612, 618
        }
    }
}
